---
- name: naistaluje vsechny potrebne programy na node a take je nastavi
  hosts: all
  tasks:

  - name: instalace dalsich repozitaru
    yum:
      name: epel-release
      state: installed

  - name: update yumu
    yum:
      state: latest

  - name: instalace potrebnych programu
    yum: 
      name:
        - apache
        - htop 
        - nginx
      state: installed
  - name: APACHE ujistime se ze bezi
    service:
      name: httpd
      state: started
  - name: APACHE otevreni portu pro http
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: APACHE restartovani firewalld kvuli nacteni novych nastaveni
    service:
      name: firewalld
      state: restarted 
