---
- name: naistaluje vsechny potrebne programy na node a take je nastavi
  hosts: all
  tasks:

  - name: instalace dalsich repozitaru pro htop
    yum:
      name: epel-release
      state: installed
  - name: instalace dalsich repozitaru pro mysql
    get_url: 
      url: http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
      dest: /opt
  - name: instalace dalsich repozitaru pro mysql
    yum:
      name: /opt/mysql57-community-release-el7-9.noarch.rpm
      state: present
  - name: update yumu
    yum:
      state: latest

  - name: instalace potrebnych programu
    yum: 
      name:
        - httpd
        - htop 
        - nginx
        - postgresql-server
        - postgresql-contrib
        - mysql-server
    #    - mysql-client
    #    - python-mysqldb
      state: installed
  - name: APACHE ujistime se ze bezi
    service:
      name: httpd
      state: started
  - name: APACHE otevreni portu pro http
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: APACHE restartovani firewalld kvuli nacteni novych nastaveni
    service:
      name: firewalld
      state: restarted 
  
  #- name: NGINX start
  #  service:
   #   name: nginx
    #  state: started

  # UDELA SE JEN JEDNOU!!! POVOLIT na zkousku - name: POSTGRESQL pomuze to nahodit
   # command: postgresql-setup initdb
   
  - name: POSTGRESQL startuje
    shell: systemctl start postgresql



