---
- name: instalace portaineru
  hosts: all
  tasks:
  - name: instalace dockeru
    yum:
      name: docker
      state: installed
  - name: startovaní dockeru
    service:
      name: docker
      state: started
  - name: povolení dockeru
    command: systemctl enable docker
  - name: pull
    command: docker pull portainer/portainer
  - name: spusteni portaineru
    command: docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer

